---
- name: "(CentOS) Add NGINX Repository"
  yum_repository:
    name: nginx
    description: Mainline CentOS NGINX Repository
    baseurl: https://nginx.org/packages/mainline/centos/{{ansible_distribution_major_version|int}}/$basearch/
    enabled: yes
    gpgkey: https://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
  when: ansible_distribution == "CentOS"

- name: "(RedHat) Add NGINX Repository"
  yum_repository:
    name: nginx
    description: Mainline RedHat NGINX Repository
    baseurl: https://nginx.org/packages/mainline/rhel/{{ansible_distribution_major_version|int}}/$basearch/
    enabled: yes
    gpgkey: https://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
  when: ansible_distribution == "RedHat"
