---
- name: "(Debian/Ubuntu) Add NGINX Signing Key"
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key

- name: "(Debian/Ubuntu) Add NGINX Repository"
  apt_repository:
    repo: "{{item}}"
  with_items:
    - deb https://nginx.org/packages/mainline/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx
    - deb-src https://nginx.org/packages/mainline/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx
